name: surf_practice_magic_ball
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.3 # Dart SDK version
  flutter: 3.10.3 # Flutter SDK version

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  shake: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
flutter:
  assets:
    - assets/mask_group_light.png
    - assets/ellipse_light.png
    - assets/error_ball.png
    - assets/error_ellipse.png
  fonts:
    - family: GillSans
      fonts:
        - asset: fonts/gill_sans.ttf

  uses-material-design: true
